import type { Lang } from "@/lib/i18n";

export type NehemiahWallLocalizedCopy = {
  title: (name: string) => string;
  keyword: string;
  fallbackTitle: string;
  stageLabels: readonly string[];
  stageDescriptions: readonly string[];
  popupTitle: string;
  popupCheck: string;
  popupButton: string;
  startNotice: string;
  completionNotice: string;
  completionButton: string;
};

const COPY: Record<Lang, NehemiahWallLocalizedCopy> = {
  ko: {
    title: (name) => `${name} 님의 느헤미야 성벽`,
    keyword: "느헤미야 성벽",
    fallbackTitle: "느헤미야 성벽",
    stageLabels: [
      "기도",
      "왕의 명령 편지",
      "예루살렘으로 이동",
      "등불을 들고 성벽을 점검",
      "돌 운반",
      "돌 운반",
      "돌 운반",
      "성문·들보 작업",
      "성문 주변 돌 운반",
      "52일 만에 성벽 중수 완료",
      "돌아오는 사람들을 환영",
      "에스라의 말씀을 경청",
      "소고·탬버린으로 찬양",
      "성벽 봉헌 찬양",
    ],
    stageDescriptions: [
      "무너진 예루살렘 성벽을 바라보며 하나님께 기도해요.",
      "왕의 명령이 담긴 편지를 읽으며 예루살렘으로 갈 준비를 해요.",
      "예루살렘을 향해 걸음을 옮겨요.",
      "등불을 들고 무너진 성벽을 점검해요.",
      "성벽을 다시 세울 돌을 나르기 시작해요.",
      "계속 돌을 나르며 성벽 중수를 이어가요.",
      "성벽이 점점 높아지도록 돌을 옮겨요.",
      "성문과 들보를 세우며 공사를 이어가요.",
      "성문 주변을 마무리하기 위해 돌을 나르며 힘을 보태요.",
      "52일 만에 성벽 중수가 완료됐어요. 함께 기뻐해요!",
      "예루살렘으로 돌아오는 사람들을 기쁘게 맞이해요.",
      "에스라가 들려주는 하나님의 말씀을 귀 기울여 들어요.",
      "소고와 탬버린을 흔들며 하나님을 찬양해요.",
      "완성된 성벽을 하나님께 봉헌하며 더욱 기쁘게 찬양해요.",
    ],
    popupTitle: "루츠맨이 성벽을 함께 세우고 있어요",
    popupCheck: "느헤미야 성벽 여정을 확인해보세요",
    popupButton: "성벽 보러 가기",
    startNotice: "느헤미야와 함께 예루살렘 성벽을 다시 세워가요.",
    completionNotice: "느헤미야 성벽 여정을 완주했어요!\n다음 말씀 여정은 준비 중이에요.",
    completionButton: "완성된 성벽 보러 가기",
  },
  en: {
    title: (name) => `${name}'s Nehemiah Wall`,
    keyword: "Nehemiah Wall",
    fallbackTitle: "Nehemiah Wall",
    stageLabels: [
      "Prayer",
      "The king's sealed letter",
      "Journey to Jerusalem",
      "Walking the wall by lantern light",
      "Carrying stones",
      "Carrying stones",
      "Carrying stones",
      "Working on the gates and beams",
      "Carrying stones near the gates",
      "Greeting by the completed wall",
      "Welcoming those returning",
      "Listening to Ezra read the Word",
      "Praising with tambourines",
      "Dedication praise",
    ],
    stageDescriptions: [
      "Pray to God while looking toward Jerusalem's broken wall.",
      "Read the king's sealed letter and prepare to go to Jerusalem.",
      "Set out on the journey toward Jerusalem.",
      "Walk along the broken wall at night with a lantern.",
      "Begin carrying stones to rebuild the wall.",
      "Keep carrying stones as the rebuilding continues.",
      "Move more stones as the wall rises higher.",
      "Continue the work by setting up the gates and beams.",
      "Carry stones to help finish the area around the gates.",
      "Rejoice and wave in front of the completed wall.",
      "Joyfully welcome the people returning to Jerusalem.",
      "Listen closely as Ezra reads God's Word.",
      "Praise God with joyful tambourines.",
      "Dedicate the completed wall to God with even greater praise.",
    ],
    popupTitle: "Rootsman is helping rebuild the wall",
    popupCheck: "See the Nehemiah Wall journey",
    popupButton: "Go to the wall",
    startNotice: "Walk with Nehemiah as Jerusalem's wall is rebuilt.",
    completionNotice: "You completed the Nehemiah Wall journey!\nThe next Word journey is being prepared.",
    completionButton: "View the completed wall",
  },
  de: {
    title: (name) => `${name}s Nehemia-Mauer`,
    keyword: "Nehemia-Mauer",
    fallbackTitle: "Nehemia-Mauer",
    stageLabels: [
      "Gebet",
      "Der versiegelte Brief des Königs",
      "Aufbruch nach Jerusalem",
      "Mit der Laterne an der Mauer entlang",
      "Steine tragen",
      "Steine tragen",
      "Steine tragen",
      "Arbeit an Toren und Balken",
      "Steine an den Toren tragen",
      "Gruß vor der vollendeten Mauer",
      "Die Rückkehrenden willkommen heißen",
      "Esras Lesung des Wortes hören",
      "Lobpreis mit Tamburin",
      "Lobpreis zur Einweihung",
    ],
    stageDescriptions: [
      "Bete zu Gott mit Blick auf die zerstörte Mauer Jerusalems.",
      "Lies den versiegelten Brief des Königs und bereite dich auf Jerusalem vor.",
      "Mach dich auf den Weg nach Jerusalem.",
      "Geh nachts mit einer Laterne an der zerstörten Mauer entlang.",
      "Beginne, Steine für den Wiederaufbau der Mauer zu tragen.",
      "Trage weiter Steine und setze den Wiederaufbau fort.",
      "Bewege weitere Steine, während die Mauer höher wird.",
      "Setze die Arbeit an Toren und Balken fort.",
      "Trage Steine, um den Bereich um die Tore fertigzustellen.",
      "Freue dich vor der vollendeten Mauer und winke.",
      "Heiße die Menschen, die nach Jerusalem zurückkehren, freudig willkommen.",
      "Hör aufmerksam zu, wie Esra Gottes Wort vorliest.",
      "Lobe Gott voller Freude mit dem Tamburin.",
      "Weihe die vollendete Mauer Gott mit noch größerem Lobpreis.",
    ],
    popupTitle: "RootsMan hilft beim Wiederaufbau der Mauer",
    popupCheck: "Schau dir die Nehemia-Mauer an",
    popupButton: "Zur Mauer",
    startNotice: "Baue mit Nehemia die Mauer Jerusalems wieder auf.",
    completionNotice: "Du hast die Reise an der Nehemia-Mauer vollendet!\nDer nächste Weg mit dem Wort wird vorbereitet.",
    completionButton: "Vollendete Mauer ansehen",
  },
  fr: {
    title: (name) => `Muraille de Néhémie de ${name}`,
    keyword: "Muraille de Néhémie",
    fallbackTitle: "Muraille de Néhémie",
    stageLabels: [
      "Prière",
      "La lettre scellée du roi",
      "En route vers Jérusalem",
      "Marcher le long de la muraille avec une lampe",
      "Transporter des pierres",
      "Transporter des pierres",
      "Transporter des pierres",
      "Travail sur les portes et les poutres",
      "Transporter des pierres près des portes",
      "Saluer devant la muraille achevée",
      "Accueillir ceux qui reviennent",
      "Écouter Esdras lire la Parole",
      "Louer avec des tambourins",
      "Louange pour la dédicace",
    ],
    stageDescriptions: [
      "Prie Dieu en regardant la muraille détruite de Jérusalem.",
      "Lis la lettre scellée du roi et prépare-toi à partir pour Jérusalem.",
      "Mets-toi en route vers Jérusalem.",
      "Marche de nuit le long de la muraille détruite avec une lampe.",
      "Commence à transporter des pierres pour reconstruire la muraille.",
      "Continue à transporter des pierres pendant la reconstruction.",
      "Transporte davantage de pierres à mesure que la muraille s'élève.",
      "Poursuis le travail sur les portes et les poutres.",
      "Transporte des pierres pour achever les abords des portes.",
      "Réjouis-toi devant la muraille achevée et salue avec joie.",
      "Accueille avec joie ceux qui reviennent à Jérusalem.",
      "Écoute attentivement Esdras lire la Parole de Dieu.",
      "Loue Dieu avec joie au son des tambourins.",
      "Consacre la muraille achevée à Dieu dans une louange encore plus joyeuse.",
    ],
    popupTitle: "RootsMan participe à la reconstruction de la muraille",
    popupCheck: "Découvre le chemin de la muraille de Néhémie",
    popupButton: "Voir la muraille",
    startNotice: "Reconstruisons la muraille de Jérusalem avec Néhémie.",
    completionNotice: "Tu as terminé le chemin de la muraille de Néhémie !\nLe prochain chemin avec la Parole est en préparation.",
    completionButton: "Voir la muraille achevée",
  },
  es: {
    title: (name) => `Muralla de Nehemías de ${name}`,
    keyword: "Muralla de Nehemías",
    fallbackTitle: "Muralla de Nehemías",
    stageLabels: [
      "Oración",
      "La carta sellada del rey",
      "Camino a Jerusalén",
      "Recorriendo la muralla con una lámpara",
      "Transportando piedras",
      "Transportando piedras",
      "Transportando piedras",
      "Trabajo en las puertas y vigas",
      "Transportando piedras junto a las puertas",
      "Saludo frente a la muralla terminada",
      "Dando la bienvenida a quienes regresan",
      "Escuchando a Esdras leer la Palabra",
      "Alabanza con panderos",
      "Alabanza de dedicación",
    ],
    stageDescriptions: [
      "Ora a Dios mientras contemplas la muralla derribada de Jerusalén.",
      "Lee la carta sellada del rey y prepárate para ir a Jerusalén.",
      "Ponte en camino hacia Jerusalén.",
      "Recorre de noche la muralla derribada llevando una lámpara.",
      "Comienza a transportar piedras para reconstruir la muralla.",
      "Sigue transportando piedras mientras avanza la reconstrucción.",
      "Lleva más piedras a medida que la muralla se levanta.",
      "Continúa el trabajo en las puertas y las vigas.",
      "Transporta piedras para terminar la zona alrededor de las puertas.",
      "Alégrate frente a la muralla terminada y saluda con gozo.",
      "Recibe con alegría a quienes regresan a Jerusalén.",
      "Escucha atentamente mientras Esdras lee la Palabra de Dios.",
      "Alaba a Dios con alegría usando panderos.",
      "Dedica a Dios la muralla terminada con una alabanza aún más gozosa.",
    ],
    popupTitle: "Rootsman está ayudando a reconstruir la muralla",
    popupCheck: "Mira el camino de la muralla de Nehemías",
    popupButton: "Ir a la muralla",
    startNotice: "Reconstruyamos la muralla de Jerusalén junto a Nehemías.",
    completionNotice: "¡Completaste el camino de la muralla de Nehemías!\nEstamos preparando el próximo camino con la Palabra.",
    completionButton: "Ver la muralla terminada",
  },
};

export function getNehemiahWallCopy(lang: Lang) {
  return COPY[lang] ?? COPY.ko;
}

export function getNehemiahWallStageLabel(lang: Lang, stageNumber: number) {
  const copy = getNehemiahWallCopy(lang);
  return copy.stageLabels[Math.max(0, Math.min(stageNumber - 1, copy.stageLabels.length - 1))] ?? copy.stageLabels[0];
}

export function getNehemiahWallStageDescription(lang: Lang, stageNumber: number) {
  const copy = getNehemiahWallCopy(lang);
  return copy.stageDescriptions[Math.max(0, Math.min(stageNumber - 1, copy.stageDescriptions.length - 1))] ?? copy.stageDescriptions[0];
}
