const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const transpile=source=>ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const m={exports:{}};vm.runInNewContext(transpile(fs.readFileSync('lib/authErrorCopy.ts','utf8')),{module:m,exports:m.exports,navigator:{onLine:true}});const notice=m.exports.authErrorNotice;
function handler(page,name){const source=fs.readFileSync(`app/${page}/page.tsx`,'utf8'),tree=ts.createSourceFile('page.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let fn;function visit(n){if(ts.isFunctionDeclaration(n)&&n.name?.text===name)fn=n;ts.forEachChild(n,visit);}visit(tree);assert.ok(fn);return transpile(fn.getText(tree));}
function setup(page,response){const state={loading:false,calls:0,error:'',routes:[]};const context={console:{error(){}},email:'fixture@example.invalid',password:'fixture-password',nickname:'fixture',lang:'ko',passwordRequestBusy:{current:false},resetLoading:false,oauthLoading:null,noticeKey:{current:''},startObservation:()=>null,setLoading:v=>state.loading=v,setError:v=>state.error=v,setResetMessage(){},authErrorNotice:notice,observeAuthRequest:(_f,run)=>run(),createClient:()=>({auth:{signInWithPassword:async()=>{state.calls++;return response();},signUp:async()=>{state.calls++;return response();}}}),setPreferredLang:async()=>{},saveLangLocally:()=>1,saveProfilePreferences:async()=>{},document:{documentElement:{dataset:{}},activeElement:null},HTMLElement:class{},router:{push:v=>state.routes.push(v),refresh(){}},getSafeRedirectFromLocation:()=>'/'};vm.createContext(context);const name=page==='login'?'handleLogin':'handleSignup';vm.runInContext(handler(page,name),context);return{state,context,run:()=>context[name]()};}
let checks=0;async function check(name,run){await run();checks++;console.log('PASS '+name);}
(async()=>{
 await check('credential/duplicate/rate/server/network errors have distinct safe notices in five languages',async()=>{for(const [error,key] of [[{code:'invalid_credentials'},'auth_credentials'],[{code:'user_already_exists'},'auth_duplicate'],[{status:429},'auth_rate'],[{status:503},'auth_unavailable'],[{name:'AuthRetryableFetchError'},'auth_network'],[{code:'__proto__',message:'PRIVATE'},'auth_generic']])for(const lang of ['ko','en','de','fr','es']){const n=notice(error,lang);assert.equal(n.key,key);assert.ok(n.text.length>10);assert.ok(!n.text.includes('PRIVATE'));}});
 await check('login returned error releases the loading state with the correct notice',async()=>{const h=setup('login',async()=>({error:{code:'invalid_credentials'}}));await h.run();assert.equal(h.state.loading,false);assert.equal(h.context.noticeKey.current,'auth_credentials');assert.equal(h.state.routes.length,0);});
 await check('thrown login request releases the lock instead of leaving a stuck form',async()=>{const h=setup('login',async()=>{throw {name:'AuthRetryableFetchError'};});await h.run();assert.equal(h.state.loading,false);assert.equal(h.context.passwordRequestBusy.current,false);assert.equal(h.context.noticeKey.current,'auth_network');});
 await check('rapid Enter/click sends one password request',async()=>{let release;const h=setup('login',()=>new Promise(r=>release=r));const first=h.run();await h.run();assert.equal(h.state.calls,1);release({error:null});await first;assert.deepEqual(h.state.routes,['/']);});
 await check('duplicate signup is explained and remains retryable',async()=>{const h=setup('signup',async()=>({data:{user:null},error:{code:'user_already_exists'}}));await h.run();assert.equal(h.context.noticeKey.current,'auth_duplicate');assert.equal(h.state.loading,false);await h.run();assert.equal(h.state.calls,2);});
 console.log(`${checks} auth UI checks passed.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
